/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.MatchRequestRole;

import Business.Organization.Broker.MngRequest;
import Business.Organization.Exchange.MatcherOrganization;
import Business.Organization.Organization;
import Interface.FeedbackMessage.FeedbackMessageJPanel;
import NewUI.LayoutMnger;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lm
 */
public class WorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaJPanel
     */
    public WorkAreaJPanel() {
        initComponents();
    }
    private JPanel userProcessContainer;
    private Organization org;
    
    public WorkAreaJPanel(LayoutMnger bot, Organization org) {
        initComponents();
        userProcessContainer = bot.getUps();
        this.org = org;
        valueLabel.setText(org.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuyRequest = new javax.swing.JButton();
        btnSellRequest = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        btnBuyRequest.setText("Show Buy Request");
        btnBuyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyRequestActionPerformed(evt);
            }
        });

        btnSellRequest.setText("Show Sell Request");
        btnSellRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellRequestActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBuyRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSellRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuyRequest)
                .addContainerGap(474, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellRequestActionPerformed
        // TODO add your handling code here:
        FeedbackMessageJPanel feedbackjp = new FeedbackMessageJPanel(userProcessContainer, this.org, "sell", null);
//        userProcessContainer.add("ViewRequestJPanel", vrjp);
        userProcessContainer.add("FeedbackMessageJPanel", feedbackjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnSellRequestActionPerformed

    private void btnBuyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyRequestActionPerformed
        // TODO add your handling code here:
        FeedbackMessageJPanel feedbackjp = new FeedbackMessageJPanel(userProcessContainer, this.org, "buy", null);
//        userProcessContainer.add("ViewRequestJPanel", vrjp);
        userProcessContainer.add("FeedbackMessageJPanel", feedbackjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyRequest;
    private javax.swing.JButton btnSellRequest;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
