/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.Account.Account;
import Business.EcoSystem;
import Business.Enterprise.CoinEnterprise;
import Business.Network.Network;
import Business.Network.NetworkDirectory;
import Business.Wallet.Wallet;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author lm
 */
public class AddWalletJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddWalletJPanel
     */
    JPanel userProcessContainer;
    private Account account;

    public JPanel getUserProcessContainer() {
        return userProcessContainer;
    }

    public void setUserProcessContainer(JPanel userProcessContainer) {
        this.userProcessContainer = userProcessContainer;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }
    public AddWalletJPanel(JPanel userProcessContainer, Account account) {
        initComponents();
        coinJComboBox.setEnabled(true);
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateComboBox();
    }
    public void populateComboBox(){
        coinJComboBox.removeAllItems();
        ArrayList<Network> networkDir = EcoSystem.getEcoSystem().getNetworkDirectory().getNetworkDirectory();
        for(Network n: networkDir){
            CoinEnterprise ce = n.getCoinEnter();
            Wallet cw = ce.getWalletDirectory().searchWalletViaCustomer(this.account.getCus());
            if(cw == null){
                coinJComboBox.addItem(n.getCoinEnter()); 
            }
            
        }
        int num = coinJComboBox.getItemCount();
        if(num == 0){
            coinJComboBox.setEnabled(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coinJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnCreateWallet = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        coinJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        coinJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coinJComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Coin Type");

        btnCreateWallet.setText("Add wallet");
        btnCreateWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWalletActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(coinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnCreateWallet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(55, 55, 55)
                .addComponent(btnCreateWallet)
                .addGap(117, 117, 117)
                .addComponent(backjButton1)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void coinJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coinJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coinJComboBoxActionPerformed

    private void btnCreateWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWalletActionPerformed
        CoinEnterprise ce = (CoinEnterprise) coinJComboBox.getSelectedItem();
        ce.getWalletDirectory().addWallet(this.account.getCus());
    }//GEN-LAST:event_btnCreateWalletActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton btnCreateWallet;
    private javax.swing.JComboBox coinJComboBox;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
