/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.Account.Account;
import Interface.FeedbackMessage.FeedbackMessageJPanel;
import NewUI.DisplayPanel.CustomerBalancePanel;
import NewUI.DisplayPanel.DollarPanel;
import NewUI.LayoutMnger;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author huali
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Account account;
    public CustomerWorkAreaJPanel(LayoutMnger bot, Account account) {
        initComponents();
        userProcessContainer = bot.getUps();
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transjButton = new javax.swing.JButton();
        historyjButton1 = new javax.swing.JButton();
        btnAddWallet = new javax.swing.JButton();
        balanceBtn = new javax.swing.JButton();
        balanceBtn1 = new javax.swing.JButton();
        btnCheckWallet = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        transjButton.setText("Submit Buy/Sell Application");
        transjButton.setActionCommand("Submit Buy/Sell Request");
        transjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transjButtonActionPerformed(evt);
            }
        });

        historyjButton1.setText("View Transaction History");
        historyjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyjButton1ActionPerformed(evt);
            }
        });

        btnAddWallet.setText("Add Wallet");
        btnAddWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWalletActionPerformed(evt);
            }
        });

        balanceBtn.setText("Check my Crypto");
        balanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtnActionPerformed(evt);
            }
        });

        balanceBtn1.setText("View Price Chart");
        balanceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtn1ActionPerformed(evt);
            }
        });

        btnCheckWallet.setText("Check my dollar wallet");
        btnCheckWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckWalletActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCheckWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(balanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(balanceBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(historyjButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAddWallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transjButton)
                .addGap(18, 18, 18)
                .addComponent(historyjButton1)
                .addGap(18, 18, 18)
                .addComponent(balanceBtn)
                .addGap(18, 18, 18)
                .addComponent(balanceBtn1)
                .addGap(18, 18, 18)
                .addComponent(btnCheckWallet)
                .addContainerGap(214, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transjButtonActionPerformed
        // TODO add your handling code here:
        SubmitRequestJPanel srjp = new SubmitRequestJPanel(userProcessContainer, account);
        userProcessContainer.add("SubmitRequestJPanel", srjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_transjButtonActionPerformed

    private void historyjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyjButton1ActionPerformed
        // TODO add your handling code here:
//        ViewRequestJPanel vrjp = new ViewRequestJPanel(userProcessContainer, account);
        FeedbackMessageJPanel feedbackjp = new FeedbackMessageJPanel(userProcessContainer, null, null, this.account);
//        userProcessContainer.add("ViewRequestJPanel", vrjp);
        userProcessContainer.add("FeedbackMessageJPanel", feedbackjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_historyjButton1ActionPerformed

    private void btnAddWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWalletActionPerformed
        // TODO add your handling code here:
        AddWalletJPanel addWallet = new AddWalletJPanel(userProcessContainer, account);
        userProcessContainer.add("AddWalletJPanel", addWallet);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddWalletActionPerformed

    private void balanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtnActionPerformed
        // TODO add your handling code here:
        CustomerBalancePanel balancePanel = new CustomerBalancePanel(account.getCus(),userProcessContainer);
        userProcessContainer.add("CheckBalanceJPanel",balancePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_balanceBtnActionPerformed

    private void balanceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtn1ActionPerformed
        // TODO add your handling code here:
        PriceChartJPanel pricePanel = new PriceChartJPanel(userProcessContainer, account);
        userProcessContainer.add("PriceChartJPanel",pricePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_balanceBtn1ActionPerformed

    private void btnCheckWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckWalletActionPerformed
        // TODO add your handling code here:
        DollarPanel dollarPanel = new DollarPanel(account.getCus(),userProcessContainer);
        userProcessContainer.add("dollarPanel",dollarPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckWalletActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DollarPanel dollarPanel = new DollarPanel(account.getCus(),userProcessContainer);
        userProcessContainer.add("dollarPanel",dollarPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceBtn;
    private javax.swing.JButton balanceBtn1;
    private javax.swing.JButton btnAddWallet;
    private javax.swing.JButton btnCheckWallet;
    private javax.swing.JButton historyjButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton transjButton;
    // End of variables declaration//GEN-END:variables
}
