/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.Account.Account;
import Business.Chart;
import Business.EcoSystem;
import Business.Enterprise.BrokerEnterprise;
import Business.Enterprise.CoinEnterprise;
import Business.Enterprise.ExchangeEnterprise;
import Business.Network.Network;
import Business.Organization.Exchange.MatcherOrganization;
import Business.Wallet.Wallet;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author huali
 */
public class PriceChartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PriceChartJPanel
     */
    
    JPanel userProcessContainer;
    private Account account;
    
    public PriceChartJPanel(JPanel userProcessContainer, Account account) {
        initComponents();  
        coinJComboBox.setEnabled(true);
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateComboBox();
    }
    
    public void populateComboBox(){
        coinJComboBox.removeAllItems();
        ArrayList<Network> networkDir = EcoSystem.getEcoSystem().getNetworkDirectory().getNetworkDirectory();
        for(Network n: networkDir){            
            coinJComboBox.addItem(n.getCoinEnter());                       
        }
        int num = coinJComboBox.getItemCount();
        if(num == 0){
            coinJComboBox.setEnabled(false);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        coinJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("View Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        coinJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        coinJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coinJComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Coin Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(coinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(coinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(411, Short.MAX_VALUE)
                    .addComponent(backjButton1)
                    .addGap(88, 88, 88)))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CoinEnterprise ce = (CoinEnterprise) coinJComboBox.getSelectedItem();            
        
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Network n = EcoSystem.getEcoSystem().getNetwork(ce.getCoinType());
        ExchangeEnterprise e = n.getExchangeEnter();
        MatcherOrganization m = (MatcherOrganization) e.getOrganization("Match");
        
        ArrayList<Integer> list = m.dealPriceList; 
        Object[] price = list.toArray();
        
        Chart chart = new Chart("Browser Price trend", "Show Price", price);
        chart.pack( );   
        RefineryUtilities.centerFrameOnScreen( chart );          
        chart.setVisible( true ); 
//        XYSeries series1 = new XYSeries("");                  
    
//        XYSeriesCollection dataset = new XYSeriesCollection(); 
//        dataset.addSeries(series1);           
//        
//        JFreeChart chart = ChartFactory.createXYLineChart("Price trend", "Count", "Price", dataset, PlotOrientation.VERTICAL, false, true, false);
//        chart.setBackgroundPaint(Color.gray);
//        chart.getTitle().setPaint(Color.red);
//        CategoryPlot p = chart.getCategoryPlot();
//        p.setRangeGridlinePaint(Color.blue);
//        ChartFrame frame = new ChartFrame("Line Chart for Price Trending", chart);
//        frame.setVisible(true);
//        frame.setSize(450, 350);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void coinJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coinJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coinJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JComboBox coinJComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
