/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewUI.DisplayPanel;

import Business.Account.Account;
import NewUI.LayoutMnger;
import Business.EcoSystem;
import Business.Email;
import Business.Enterprise.AbstractEnterprise;
import Business.Enterprise.Role.Customer;
import Business.Enterprise.Role.Miner;
import Business.Network.Network;
import Business.Organization.Organization;
import NewUI.NewJFrame;
import NewUI.UserControlPanel.AfterLoginPanel;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author summershoohaw
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    private LayoutMnger bot;
    private LayoutMnger top;
    private LayoutMnger right;
    private LayoutMnger total;
    
    public RegisterPanel(LayoutMnger bot,LayoutMnger top,LayoutMnger right,LayoutMnger total) {
        initComponents();
        this.bot = bot;
        this.top = top;
        this.right = right;
        this.total = total;
    }
    
    
    
    public void sendEmail(String title){
        String[] emailReceipeint = {emailText.getText()};
        Email smtpMailSender = new Email();
        String item = "Username: "+userTxt.getText() + "        Password:" + pwTxt.getText();
        try {
            smtpMailSender.postMail(emailReceipeint, title, item, Email.getSMTP_AUTH_USER());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Send Email Failed");
                    
        }
    }
    
    public void autoLogin(){
        String userName = userTxt.getText();
        // Get Password
        String password = pwTxt.getText();

        //Step1: Check in the system admin user account directory if you have the user
        Account userAccount = EcoSystem.getEcoSystem().getAccountDir().authenticateUser(userName, password);

        AbstractEnterprise inEnterprise=null;
        Organization inOrganization=null;

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:EcoSystem.getEcoSystem().getNetworkDirectory().getNetworkDirectory()){
                //Step 2.a: check against each enterprise
                for(AbstractEnterprise enterprise:network.getEnterpriseDir().getEnterpriseDir()){
                    userAccount=enterprise.getAccountDir().authenticateUser(userName, password);
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrgDir().getOrgList()){
                            userAccount=organization.getAccountDir().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            JPanel newWorkArea = userAccount.getRole().createWorkArea(right, userAccount, inOrganization, inEnterprise, EcoSystem.getEcoSystem());
            total.getLayout().show(total.getUps(),"card3");
            NewJFrame.getjSplitPane2().setVisible(true);
            bot.next(newWorkArea);
            top.next(new AfterLoginPanel(userAccount,bot,top,right,total));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        createJButton = new javax.swing.JButton();
        passwordText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        createCusBtn = new javax.swing.JButton();
        pwTxt = new javax.swing.JTextField();
        createMinerBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        userNameJTextField2 = new javax.swing.JTextField();
        nameTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        createJButton.setLabel("Create Account");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        createCusBtn.setText("Register as customer");
        createCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCusBtnActionPerformed(evt);
            }
        });

        createMinerBtn.setText("Register as miner");
        createMinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMinerBtnActionPerformed(evt);
            }
        });

        nameTxt.setText("Name");

        emailTxt.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(backJButton1)
                        .addGap(82, 82, 82)
                        .addComponent(createCusBtn)
                        .addGap(48, 48, 48)
                        .addComponent(createMinerBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxt)
                            .addComponent(emailTxt))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCusBtn)
                    .addComponent(backJButton1)
                    .addComponent(createMinerBtn))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        total.previous();
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
//        String username = userTxt.getText();
//        String password = pwTxt.getText();
//        
//        EcoSystem.getEcoSystem().getAccountDir().createAccount(username, password, new Customer());
//        for(Account a:EcoSystem.getEcoSystem().getAccountDir().getUserAccountList()){
//            System.out.println(a.getUsername());
//        }

    }//GEN-LAST:event_createJButtonActionPerformed
    
    private void createCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCusBtnActionPerformed
        String pattern = ".*@.*\\.com";
        if(!Pattern.matches(pattern, emailText.getText())){
            JOptionPane.showMessageDialog(null, "Illegal email address! inpute like xxxx@xx.com");
            emailText.setText("");
            return;
        }
        String username = userTxt.getText();
        String password = pwTxt.getText();
        
        Account account = EcoSystem.getEcoSystem().getAccountDir().createAccount(username, password, new Customer());
        if(account == null)
            return;
        sendEmail("Hi, Customer");
        for(Account a:EcoSystem.getEcoSystem().getAccountDir().getUserAccountList()){
            System.out.println(a.getUsername());
        }
        int selection = JOptionPane.showConfirmDialog(null, "Account created successfully, do you want to log in this time?","Congrats",JOptionPane.YES_NO_OPTION);
        if(selection == JOptionPane.YES_OPTION)
            autoLogin();
        else
            total.previous();
    }//GEN-LAST:event_createCusBtnActionPerformed

    private void createMinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMinerBtnActionPerformed
        // TODO add your handling code here:
        String pattern = ".*@.*\\.com";
        if(!Pattern.matches(pattern, emailText.getText())){
            JOptionPane.showMessageDialog(null, "Illegal email address! inpute like xxxx@xx.com");
            emailText.setText("");
            return;
        }
        String username = userTxt.getText();
        String password = pwTxt.getText();
        
        Account account = EcoSystem.getEcoSystem().getAccountDir().createAccount(username, password, new Miner());
        if(account == null)
            return;
        sendEmail("Hi, Miner");
        for(Account a:EcoSystem.getEcoSystem().getAccountDir().getUserAccountList()){
            System.out.println(a.getUsername());
        }
        int selection = JOptionPane.showConfirmDialog(null, "Account created successfully, do you want to log in this time?","Congrats",JOptionPane.YES_NO_OPTION);
        if(selection == JOptionPane.YES_OPTION)
            autoLogin();
        else
            total.previous();
    }//GEN-LAST:event_createMinerBtnActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        total.previous();
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createCusBtn;
    private javax.swing.JButton createJButton;
    private javax.swing.JButton createMinerBtn;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField pwTxt;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JTextField userNameJTextField2;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
