/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.MineButton;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author lm
 */
public class MinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MinerJPanel
     */
    public MineButton[][] btnList;
    private JPanel container;
    public MinerJPanel(JPanel container) {
        initComponents();
        this.container = container;
        btnList = new MineButton[10][10];
        this.setLayout(new BorderLayout());
        addButton();
        setRandom();
    }
    
    public void addButton(){
        this.setLayout(new GridLayout(0,10));
        for(int i=0; i<10; i++){
            for(int j=0; j<10; j++){
                MineButton btn = new MineButton(i,j);
                btnList[i][j] = btn;
                btn.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e){
                        MineButton btn = (MineButton) e.getSource();
                        btn.setText(btn.value);
                        btn.setEnabled(false);
                        btn.setIsSelected(true);
                    }
                });
                this.add(btn, BorderLayout.CENTER);
               
            }
        }
        this.add(btnBack, BorderLayout.WEST);
    }
    
    public void populateBtn(){
        this.setLayout(new GridLayout(11,10));
        for(int i=0; i<btnList[0].length; i++){
            for(int j=0; j<btnList.length; j++){
                MineButton btn = btnList[i][j];
                if(btn.getIsSelected()){
                    btn.setEnabled(false);
                }
                this.add(btn, BorderLayout.CENTER);
                
            }
        }
        
    }
    
    public void setRandom(){
        for(int i = 0; i<10; i++){
            int x = (int) (Math.random() * 10);
            int y = (int) (Math.random() * 10);
            this.btnList[x][y].value = "2";
            System.out.println(y + "," + x);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 331, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 271, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
