/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewUI;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import NewUI.DisplayPanel.WelcomePanel;
import NewUI.UserControlPanel.BeforeLoginPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author summershoohaw
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private LayoutMnger top;
    private LayoutMnger bot;
    private LayoutMnger right;
    private LayoutMnger total;

    public static JSplitPane getjSplitPane2() {
        return jSplitPane2;
    }

//    public static void setjSplitPane2(JSplitPane jSplitPane2) {
//        NewJFrame.jSplitPane2 = jSplitPane2;
//        
//    }
//    
//    public static void resetSplitPane2(){
//        buttonPanel = new javax.swing.JPanel();
//        buttonPanel.setLayout(new java.awt.CardLayout());
//        jSplitPane2.setLeftComponent(buttonPanel);
//        operatePanel = new javax.swing.JPanel();
//        operatePanel.setLayout(new java.awt.CardLayout());
//        jSplitPane2.setRightComponent(operatePanel);
//    }

    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public NewJFrame() {
        initComponents();
        EcoSystem.ecoSystem = dB4OUtil.retrieveSystem();
        jSplitPane2.setVisible(false);
        top = new LayoutMnger(userControl);
        bot = new LayoutMnger(buttonPanel);
        right = new LayoutMnger(operatePanel);
        total = new LayoutMnger(displayPanel);
        top.clearAllPanel();
        bot.clearAllPanel();
        right.clearAllPanel();
        top.next(new BeforeLoginPanel(bot,top,right,total));
        total.getLayout().next(total.getUps());
        total.getUps().add(new WelcomePanel(),"Welcome");
        total.getLayout().next(total.getUps());
        this.setSize(900,700);
        this.setResizable(false);
        
        //jSplitPane1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        userControl = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        displayPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        buttonPanel = new javax.swing.JPanel();
        operatePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setEnabled(false);

        userControl.setLayout(new java.awt.CardLayout());
        userControl.add(jSeparator1, "card2");

        jSplitPane1.setTopComponent(userControl);

        displayPanel.setLayout(new java.awt.CardLayout());

        jSplitPane2.setDividerLocation(224);
        jSplitPane2.setEnabled(false);

        buttonPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setLeftComponent(buttonPanel);
        buttonPanel.getAccessibleContext().setAccessibleParent(jSplitPane2);

        operatePanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(operatePanel);

        displayPanel.add(jSplitPane2, "card3");

        jSplitPane1.setRightComponent(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private static javax.swing.JSplitPane jSplitPane2;
    private static javax.swing.JPanel operatePanel;
    private javax.swing.JPanel userControl;
    // End of variables declaration//GEN-END:variables
}
