/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewUI.UserControlPanel;

import Business.Account.Account;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import NewUI.DisplayPanel.SettingPanel;
import NewUI.LayoutMnger;
import NewUI.NewJFrame;

/**
 *
 * @author summershoohaw
 */
public class AfterLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form AfterLoginPanel
     */
    private Account account;
    private LayoutMnger bot;
    private LayoutMnger top;
    private LayoutMnger right;
    private LayoutMnger total;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public AfterLoginPanel(Account account,LayoutMnger bot,LayoutMnger top,LayoutMnger right,LayoutMnger total) {
        initComponents();
        this.account = account;
        this.top = top;
        this.bot = bot;
        this.right = right;
        this.total = total;
        showTxt.setText("Dear "+account.getCus().getName()+", welcome to CryptoCurrency trading center!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showTxt = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        showTxt.setText("show account owner's name here");

        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Change password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(showTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutBtn)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        NewJFrame.getjSplitPane2().setVisible(false);
        bot.clearAllPanel();
        top.clearAllPanel();
        right.clearAllPanel();
        top.next(new BeforeLoginPanel(bot,top,right,total));
        total.getLayout().show(total.getUps(),"Welcome");
        dB4OUtil.storeSystem(EcoSystem.getEcoSystem());
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SettingPanel sp = new SettingPanel(account, right);
        right.next(sp);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel showTxt;
    // End of variables declaration//GEN-END:variables
}
